### ISSUE TITLE
It seems that the pre-training phase is not functioning.

### ISSUE THREAD

**Issue by xianfan666** [zfan20/GraphDA#1]
Hello! Thank you for sharing the code for GraphDA, but it seems there is an issue with the code. Specifically, the running command for the pre-training phase appears to be incorrect, which prevents the pre-training part from running.

**Comment by zfan20** [comment]
sorry for the naming issue, updated.

**Comment by TaoWang666** [comment]
Thank you, I have identified the command error, and now the code is running correctly.
