### ISSUE TITLE
The experimental results seem to differ from what is mentioned in the paper.

### ISSUE THREAD

**Issue by TaoWang666** [zfan20/GraphDA#2]
Hello! It seems that when I replicated your code yesterday and ran the Enhanced-UI and GraphDA experiments using the provided commands, the reproduced results did not match the actual data mentioned in your paper. Specifically, the experimental data for Enhanced-UI was significantly higher than the actual data in your paper, while the experimental data for GraphDA was slightly lower than the actual data in your paper.

This is the replication result for Enhanced-UI.
<img width="945" alt="Enhanced-UI" src="https://github.com/zfan20/GraphDA/assets/113903912/2bb12211-ddaf-4495-9882-725d62a70860">

This is the replication result for GraphDA.
<img width="945" alt="GraphDA" src="https://github.com/zfan20/GraphDA/assets/113903912/e9de568e-5838-42f4-ab13-6232fbaeba8a">

**Comment by zfan20** [comment]
As usual, again, the reported results come from the grid-searched experiments instead of one single run. It does not make sense to run all methods (baselines and our methods) in only one shot. The command shown in the readme is only an example to run.

**Comment by TaoWang666** [comment]
Thank you very much for your response!
